### ISSUE TITLE
Bad link 

### ISSUE THREAD

**Issue by mroswell** [nytimes/library#102]
### Context (Environment)

https://open.nytimes.com/we-built-a-collaborative-documentation-site-deploy-your-own-with-the-push-of-a-button-134de99c42fc

### Expected Behavior
It's important to get the links right, because this is the most Google-findable result for this project. 

### Actual Behavior
 
This link "on the documentation site" on 
https://open.nytimes.com/we-built-a-collaborative-documentation-site-deploy-your-own-with-the-push-of-a-button-134de99c42fc
points to
https://nyt-library-demo.appspot.com/get-started/deploying-library-google-app-engine 
which yields a 500 error

### To Reproduce

Just click on the link described above to see the 500 error

**Comment by isaacwhite** [comment]
🙌  @shawn620, who redeployed to app engine demo to fix this.
