### ISSUE TITLE
eslint failing on master branch

### ISSUE THREAD

**Issue by gregbarasch** [nytimes/library#141]
### Context (Environment)
Linux Mint 19.3
Kernel 5.3.0-51-generic

`npm -version` 
6.14.5

`node -v` 
v14.0.0

### Expected Behavior
`npm run lint` runs, and no errors experienced

### Actual Behavior
The following behavior is experienced
> library/server/formatter.js
>   86:46  error  Parsing error: Invalid regular expression: /(?<=#heading=)([^/]+)/: Invalid group

### Possible Solution
This error is due the compatibility of what's called a "positive look behind" in regular expression land... The best way to explain what's happening here is by example:

```
decoded = "#heading=test"
decoded.match(/(?<=#heading=)([^/]+)/i)
```
returns: `test,test`

<br>

```
decoded = "#heading=test"
value = decoded.match(/#heading=([^/]+)/i))
```
returns: `#heading=test,test`

<br>

The first index value is a match for the regular expression in its entirety, while the second is a match for the group, identified by the final set of "( )" in our examples. We should be able to use my example regular expression, and do something like `if (!= null): return array[size-1]`, rather than using the positive look behind

**Comment by isaacwhite** [comment]
Closed via #157
