### ISSUE TITLE
Question: Create folder with "index" page?

### ISSUE THREAD

**Issue by voshawn** [nytimes/library#216]
### What I am trying to do
I want to create a folder with content in in "index" similar to this page: 
![image](https://user-images.githubusercontent.com/10394260/92286199-54b75580-eed4-11ea-8536-cebad341ae1e.png)

### What I have attempted so far
1. I created a folder called "Operations" then tried creating a doc called "Operations" inside of that folder. This made it so that I don't see the file in the folder listing, but I don't the content.
2. I created a folder called "Operations" then tried creating a doc called "Operations" on the same level. It gave me a warning of duplicate names.
3. I created a folder called "Operations" then tried creating a doc called "index" inside of that folder. This just made a page in the folder. 

Here is what my folder page looks like. I am expecting the content of the "Operations" doc to be on this page. 
![image](https://user-images.githubusercontent.com/10394260/92286660-a14f6080-eed5-11ea-8aa5-50ca198f35c4.png)

Here is my drive:
![image](https://user-images.githubusercontent.com/10394260/92286701-c04df280-eed5-11ea-8088-4a4e21ef9a91.png)

**Comment by isaacwhite** [comment]
Hi, @voshawn! To set text for the homepage of a folder, we [use tags](https://nyt-library-demo.herokuapp.com/how-to-use-library/how-do-i-use-tags). This means the document can be named whatever you want, as long as it contains the correct tag [home].

**Comment by voshawn** [comment]
Ah I must have missed that. Thanks for the quick response @isaacwhite! 

Awesome project by the way! I looked at a ton of tools for an internal team wiki and this seems like a perfect fit :)
