### ISSUE TITLE
Preserve deep links to other documents

### ISSUE THREAD

**Issue by abstrctn** [nytimes/library#24]
### Expected Behavior

When one library document links to another using the `docs.google.com` url, the resulting rendered version of that link should preserve deep links such as those to headings in the  document: `.../edit#heading=h.h1dswxgykb74`.

### Actual Behavior

The rendered link drops the hash from the original link. This is probably because the original link is used only to get the document ID, and the canonical URL for that document (without any deep links) is used directly:

https://github.com/nytimes/library/blob/5c08c23add3964aada2b1a48e49952cd3d5f84df/server/formatter.js#L85

### Possible Solution

The hash component of document urls could also be parsed out, and appended to the canonical url.

**Comment by isaacwhite** [comment]
Closed via #25.
