### ISSUE TITLE
Characters with diacritics are disappearing in slug

### ISSUE THREAD

**Issue by midorikocak** [nytimes/library#267]
### Context (Environment)
Used "Deploy to Heroku" button with no customization.

### Expected Behavior

When we have "Öğretmenelere Öneriler" as a doc title, we expect that character with diacritics are successfully deascified like "ogretmenlere-oneriler". In languages like Turkish or Czech diacritics are important.

### Actual Behavior
Characters with diacritics are simply disappear. "Öğretmenelere Öneriler"  becomes "retmenelere-neriler".

### To Reproduce
Simply rename a document to use diacritics like çığöşü.

### Additional Information
Badly written slugs are a big issue for non-english internet and the links are less accessible.

### Possible Solution
Slug generator could transform diacritics to it's non diacritic counterparts ş -> s, ç -> c etc.

**Comment by midorikocak** [comment]
A quick search gives this solution:
``` javascript
function slugify(text) {
  text = text.toString().toLowerCase().trim();

  const sets = [
    {to: 'a', from: '[ÀÁÂÃÄÅÆĀĂĄẠẢẤẦẨẪẬẮẰẲẴẶἀ]'},
    {to: 'c', from: '[ÇĆĈČ]'},
    {to: 'd', from: '[ÐĎĐÞ]'},
    {to: 'e', from: '[ÈÉÊËĒĔĖĘĚẸẺẼẾỀỂỄỆ]'},
    {to: 'g', from: '[ĜĞĢǴ]'},
    {to: 'h', from: '[ĤḦ]'},
    {to: 'i', from: '[ÌÍÎÏĨĪĮİỈỊ]'},
    {to: 'j', from: '[Ĵ]'},
    {to: 'ij', from: '[Ĳ]'},
    {to: 'k', from: '[Ķ]'},
    {to: 'l', from: '[ĹĻĽŁ]'},
    {to: 'm', from: '[Ḿ]'},
    {to: 'n', from: '[ÑŃŅŇ]'},
    {to: 'o', from: '[ÒÓÔÕÖØŌŎŐỌỎỐỒỔỖỘỚỜỞỠỢǪǬƠ]'},
    {to: 'oe', from: '[Œ]'},
    {to: 'p', from: '[ṕ]'},
    {to: 'r', from: '[ŔŖŘ]'},
    {to: 's', from: '[ßŚŜŞŠȘ]'},
    {to: 't', from: '[ŢŤ]'},
    {to: 'u', from: '[ÙÚÛÜŨŪŬŮŰŲỤỦỨỪỬỮỰƯ]'},
    {to: 'w', from: '[ẂŴẀẄ]'},
    {to: 'x', from: '[ẍ]'},
    {to: 'y', from: '[ÝŶŸỲỴỶỸ]'},
    {to: 'z', from: '[ŹŻŽ]'},
    {to: '-', from: '[·/_,:;\']'}
  ];

  sets.forEach(set => {
    text = text.replace(new RegExp(set.from,'gi'), set.to)
  });

  return text
    .replace(/\s+/g, '-')    // Replace spaces with -
    .replace(/[^-a-zа-я\u0370-\u03ff\u1f00-\u1fff]+/g, '') // Remove all non-word chars
    .replace(/--+/g, '-')    // Replace multiple - with single -
    .replace(/^-+/, '')      // Trim - from start of text
    .replace(/-+$/, '')      // Trim - from end of text
}

console.log(slugify('Do you know it rains?'));
console.log(slugify('víš, že prší?'));
console.log(slugify('Ști că plouă?'));
console.log(slugify('ты знаешь, что идет дождь?'));
console.log(slugify('ἀεὶ Λιβύη φέρει τι καινόν'));
```

**Comment by afischer** [comment]
Thanks for the bug report! Feel free to submit a PR if you're interested in fixing this yourself! If not, another community member or contributor may be able to pick it up.

**Comment by jrasanen** [comment]
The solution above is a bit naive, as it wouldn't convert "今日は" into anything.  Wikipedia for example just embraces the unicode [https://en.wiktionary.org/wiki/今日は](https://en.wiktionary.org/wiki/今日は).

I would suggest just making the the slug url-safe and don't transliterate characters at all.
