### ISSUE TITLE
Click to zoom on photos/modal images

### ISSUE THREAD

**Issue by afischer** [nytimes/library#268]
### Problem Description
Some photos can be difficult to see at the size library presents them. It would be great to add a way to zoom or pop open photos to a larger size on click.

### Feature
- Images should show the zoom cursor on image hover
- Clicking an image causes it to zoom, filling to the window's width or to 100% size of the image, whatever is smallest

**Comment by xvandish** [comment]
@afischer cool if I take up this work?

**Comment by afischer** [comment]
Sure! Assigned — Let me know if there's anything I can do to help.

**Comment by xvandish** [comment]
cool! sure, I'll reach out if anything
