### ISSUE TITLE
Some problems in setting it up

### ISSUE THREAD

**Issue by raimohanska** [nytimes/library#270]
Thanks for Library, looks really promising! I'm evaluating it to be used as a basis for our company (Reaktor) collaborative documentation site. I set it up using your instructions and found some errors, most likely mostly due to changes on the GCP UI. Just dumping the observations here for now with links to the pages where I stumbled into them.

1. [Creating service account](https://nyt-library-demo.herokuapp.com/get-started/create-a-service-account): "Create key" is not shown in "Create service account" wizard. Instead you'll need to click on the account after creation, then Keys->Add key. 
2. You might mention that when sharing the shared folder, you should grant "Content manager" permissions (the default).
3. In my case I had to change the "People outside Reaktor can be added to files" setting for the shared drive I'm using. Not sure if worth mentioning.
4. [Cloud datastore API](https://nyt-library-demo.herokuapp.com/get-started/enabling-the-cloud-datastore-api) I found out that DataStore is now under "Databases", not "Storage" in the GCP menu
5. Also "you should be able to fun" -> "run"
6. After "Select Datastore Mode" there were few steps, including database location selection, but that was easy.
7. I first copy-pasted the command including YOUR_PROJECT_ID_HERE until I realised that I'll need to replace the placeholder.
8. The OAuth id and secret are to be found under the OAuth client Id, not the service account, like it says on [Deploying to Heroku](https://nyt-library-demo.herokuapp.com/get-started/deploying-library-heroku): "...by going to the “Credentials” the "Credentials" page of the console's "APIs & Services" menu and clicking on the service account name."

All of this I managed through quite easily. Then after deployment it starts on Heroku and requires Google Authentication as expected. However, after that,

9. "uh on that's a 500" and logs have the following

```
2021-06-08T09:05:37.727667+00:00 app[web.1]: error: Serving an error page for /
2021-06-08T09:05:37.727678+00:00 app[web.1]: { message: 'Cannot convert undefined or null to object',
2021-06-08T09:05:37.727679+00:00 app[web.1]: stack:
2021-06-08T09:05:37.727682+00:00 app[web.1]: 'TypeError: Cannot convert undefined or null to object\n    at Function.keys (<anonymous>)\n    at buildDisplayCategories (/app/server/routes/pages.js:90:29)\n    at handlePage (/app/server/routes/pages.js:65:24)' }
```

I'm not expecting you to fix all this, just reporting the current status and I'll try to figure out what's wrong. Any pointers/help is of course appreciated! If we get this set up, and decide to give Library a go, you might expect some contributions from us :)

Anyways, huge thanks for making Library happen and open-source. Looks really good and kinda checks all of my boxes. Documentation seems very good, you've clearly put a lot of effort into this.

**Comment by raimohanska** [comment]
I created new Shared Drive and pointed Library to use that (with DRIVE_TYPE=team) and now it seems to work. I cannot seem to get it to work with a Folder as root though. Even when using a folder on this new Drive.

**Comment by jpmckinney** [comment]
I have the same error as @raimohanska, which is that a folder within a team drive doesn't seem to work (tried both `DRIVE_TYPE=folder` and `DRIVE_TYPE=team`, but a root team drive is fine (with `DRIVE_TYPE=team`).

Previously (on an older version), I had it working on a regular folder (not within a team drive), but we are switching to team drives for easier access control.

We don't want Library to read from the root of the team drive, but that's the only way it seems to work.
