### ISSUE TITLE
Question: How do I reference assets as part of a customization?

### ISSUE THREAD

**Issue by recup** [nytimes/library#281]
### What I am trying to do
I've set up a customization repo as described. It works well and I was able to override styles, colors and templates.  I'm completely stuck on how to add new assets like a custom brand image, though.

Let's say I've added a `/assets/images/new-logo.svg` to my customization repo, how would I need to reference it in a template?

Thank you!

**Comment by leranjun** [comment]
I think assets are just located in `/public`. Not sure if there is a way to overwrite it with the custom folder; might be able to achieve with a middleware…

**Comment by nzben** [comment]
Hi @recup, I've just added a change that allows you to put assets into the `/public/` folder in your customisation repo, and they will be copied into `/public/` on the deployed site. This way you can replace the logo by adding your custom logo as `/public/images/[custom logo file].png`

An example is [in our own repo](https://github.com/The-Spinoff-Group/spinoff-library-customization).

**Comment by recup** [comment]
Thank you very much, that is exactly what I was looking for!  Much appreciated.  🖖🏼
