### ISSUE TITLE
Links on images do not show up

### ISSUE THREAD

**Issue by leranjun** [nytimes/library#287]
### Context (Environment)
An installation of Library without too much customisation. (I know I'm being vague here, but I think the context should be irrelevant XD)

### Expected Behavior
Clicking on an image with a link assigned should take me to the linked site.

### Actual Behavior
It does not.

In Google Docs:
![image](https://user-images.githubusercontent.com/25704248/129340965-f17b5525-d35c-4d8c-b418-03d542aaf421.png)

Rendered DOM in Library:
![image](https://user-images.githubusercontent.com/25704248/129340991-f0c15908-8f3c-4bb5-8369-6fc5ad30c7a7.png)

No `<a>` tags at all.

### To Reproduce
1. Add an image to a Google Doc.
2. Add a link to the image by selecting the image and going to `Insert -> Link`.
3. Click on the image in Google Docs. It should display a pop up to the web page as above.
4. Click on the image in Library. Nothing happens.

**Comment by afischer** [comment]
Hi @leranjun, thanks for the bug report. Unfortunately, as noted in #52, this seems to be an API limitation. 

I've gone ahead and filed a bug report with [google here](https://issuetracker.google.com/196795442) - give it a star if you can!

Going to transfer your information over to #52 and close this as duplicate, but feel free to continue conversation over in #52!
