### ISSUE TITLE
Single backticks in code blocks getting substituted out

### ISSUE THREAD

**Issue by tarekrached** [nytimes/library#294]
### Context (Environment)
v1.4.1 in docker

### Expected Behavior
see the backticks in the code block:
![image](https://user-images.githubusercontent.com/167218/132589263-9962dbba-d4aa-463f-bb34-f5d410abe7cd.png)

### Actual Behavior
backticks are not rendered:
![image](https://user-images.githubusercontent.com/167218/132589195-9253dba2-5965-4bfb-aa82-f113e8d4e65f.png)

### To Reproduce

put the following into a doc, with a trailing triple-backtick to close the code block

```
```js
const js = `one ${true} language`
```

### Additional Information
this is referenced in the code [here](https://github.com/nytimes/library/blob/63e8a1bb9eeb9410b49806b5cfed35de1d69e3e1/server/formatter.js#L123-L126)
with the following comment
```
  // Replace single backticks with <code>, as long as they are not inside triple backticks
```

**Comment by afischer** [comment]
Hi @tarekrached, this issue should be fixed by #301. If you replace your inline backticks with double backticks (as specified in the markdown spec), they should parse correctly.

I'll cut a release in a bit to make sure this is available on Dockerhub if you're using our containerized releases.
