### ISSUE TITLE
Tall images cut off when expanded

### ISSUE THREAD

**Issue by afischer** [nytimes/library#297]
### Context (Environment)
Very tall, high resolution images can be cut off as they expand to fill the width of the window. You can not scroll down as that triggers the modal to close.

![image](https://user-images.githubusercontent.com/5422397/136601919-5c2e07c9-bb1e-4ada-a481-27a6909fb5ef.png)

### Expected Behavior

The entire image should be visible/accessible in the expanded state. 

### Actual Behavior
The image is cut off, and scrolling closes the image modal.

### Possible Solution

Either change the CSS to make the image fill the screen, or allow scrolling through the image if it is too tall.

**Comment by xvandish** [comment]
Here's a link to the image where this happens - https://library.nyt.net/features-design/section-specific-guidelines/arts-leisure#h.ar6v5m43nv4f. @afischer I'll take this up if thats ok? I can also handle the other image related bugs if they're still open!
