### ISSUE TITLE
Large document trees in shared folders exceed API limitations

### ISSUE THREAD

**Issue by isaacwhite** [nytimes/library#32]
As reported by @pfhayes, in large document trees inside a shared folder, the list of parentIds may get too long to complete in a single request. We should partition this into a maximum number of parentIds to maintain parallelization most of the time but resolve the issue that @pfhayes observed.

_Originally posted by @pfhayes in https://github.com/nytimes/library/pull/15_

**Comment by juliliza** [comment]
good issue

**Comment by isaacwhite** [comment]
Closed via @evelynting610 in #87 🥇
