### ISSUE TITLE
Inline EJS no longer renders?

### ISSUE THREAD

**Issue by leranjun** [nytimes/library#329]
### Context (Environment)
Browser: Chrome 104.0.5112.101 on macOS 10.14.6
node: v16.3.2
Library instance uses a folder.

### Expected Behavior
When `ALLOW_INLINE_CODE` is turned on and using EJS markups such as `<%-<p class="social-icons"><!-- some icons here --></p>%>`, the content should be displayed properly.

### Actual Behavior
<img width="232" alt="image" src="https://user-images.githubusercontent.com/25704248/185903765-f46de522-8ba9-4afe-85b4-75140dbaa16d.png">

### To Reproduce
I believe any instance of library would have the problem.

[The demo site](https://nyt-library-demo.herokuapp.com/how-to-use-library/supported-formats) also doesn't work, but I'm not sure if it's because `ALLOW_INLINE_CODE` is not enabled in the first place.

### Additional Information
I think Google might have changed their export format (extra escaping for HTML characters?), but I'm unfamiliar with what the original format looks like…

### Possible Solution
Not too sure, but it's gotta be somewhere in https://github.com/nytimes/library/blob/main/server/formatter.js.

**Comment by afischer** [comment]
Hi @leranjun,

We haven't had any releases recently that touch the formatter, so I don't think there would be anything that would have broken inline code. We also run an instance of Library that's using the latest version of the app, and it seems to be working just fine. 

Have you tested using the code block on the demo site?

**Comment by leranjun** [comment]
Oh my, I am absolutely dumb. I thought I turned on `ALLOW_INLINE_CODE` already, but then I remembered I did a reset and forgot to turn it back on. Sorry.
