### ISSUE TITLE
Redirect URI incorrect when running behind a https proxy. 

### ISSUE THREAD

**Issue by salexpdx** [nytimes/library#33]
### Context (Environment)
I'm running the Library application as a Fargate task fronted by an ALB that handles HTTPS offloading. Access is restricted to our corporate domain. 

### Expected Behavior
When I attempt to login, the redirect uri provided should use the same https protocol that I am using to access the library site. 

### Actual Behavior
When I initially visit the library website, I am redirected to google for authentication. This redirect URI that is sent with the request is for the correct domain but http instead of https.  

### To Reproduce
Offload HTTPS encryption outside of the application.

### Possible Solution
This appears to be caused by the application not detecting that there is https offloading going on. I've found a few possible options that might explain the behavior:

`app.enable("trust proxy");`
https://stackoverflow.com/questions/20739744/passportjs-callback-switch-between-http-and-https

`app.use(forceSsl);`
https://stackoverflow.com/questions/7185074/heroku-nodejs-http-to-https-ssl-forced-redirect

I'll be testing out the first option shortly. It seems the most direct solution that wouldn't impact others who aren't using https.  The later option seems like it would need to have an environmental variable that wraps that being enabled to ensure that only people who want to have it enabled are impacted.

**Comment by salexpdx** [comment]
Adding the `app.enable("trust proxy")` to the server/index.js file had the desired effects.  I propose that this is the best solution going forward on the basis that it shouldn't do anything to directly delivered requests or requests made via http.  

I also tried testing the force-https.js middleware found in the [customization library](https://github.com/nytimes/library-customization-example/blob/773f5e32802e14317db0bd60a5b21140b7a8e1db/middleware/force-https.js ) and it doesn't change the redirect url.

**Comment by isaacwhite** [comment]
Hey @salexpdx, thanks for digging into this. What do you think about using an environment variable to trigger this behavior? We could enable just based on `TRUST_PROXY` being present.

**Comment by salexpdx** [comment]
That seems like the safest behavior from a standpoint of don't break anyone who already has it running.  I know I can easily add an extra environment flag to my configuration.   I just tossed in a PR https://github.com/nytimes/library/pull/37 to make it work that way.
