### ISSUE TITLE
EJS template string in Google Docs are not escaped correctly when rendering

### ISSUE THREAD

**Issue by mtandre** [nytimes/library#34]
### Expected Behavior
In Google Doc:
````
```
<%- include('./../default/partials/pagination', { pages }) %>
```
````

The code snippet should render with the contents:
> 1. <%- include('./../default/partials/pagination', { pages }) %>

### Actual Behavior
The code snippet is rendered empty:
> 1. 

### Possible Solution

Is there a conflict between the EJS templating and EJS template strings?

**Comment by afischer** [comment]
Looks like [this line](https://github.com/nytimes/library/blob/master/server/formatter.js#L117) is the culprit. I'm not sure if there is a reason the app removes template strings if `ALLOW_INLINE_CODE` is not set rather than leaving them in, but @isaacwhite would know more!

**Comment by isaacwhite** [comment]
In @mtandre's case I believe `ALLOW_INLINE_CODE` was set, but you have a good point @afischer  that it's reasonable to return unescaped text from the match rather than an empty string when the env var is omitted.
