### ISSUE TITLE
Application not listing files on drive

### ISSUE THREAD

**Issue by pranayhere** [nytimes/library#39]
### Context (Environment)

Operating System : Ubuntu 18.04
node version : v10.15.1

### Expected Behavior
Web UI should list the files on the shared drive folder.

### Actual Behavior

Web UI is not listing the files on the shared drive folder.

### To Reproduce

followed the installation steps mentioned on https://nyt-library-demo.herokuapp.com/get-started

### Additional Information

I can see the application logs and it shows 
```
[0] debug: searching for files > 3
[0] debug: Current file count in drive: 2
```
And whenever I create a new file it shows `info: CACHE PURGE /first-demo FROM CHANGE AT /first-demo`

![Screen Shot 2019-06-24 at 12 50 56 AM](https://user-images.githubusercontent.com/3493868/59981026-b961f980-961b-11e9-960c-5d14e749e4db.png)
![Screen Shot 2019-06-24 at 12 52 37 AM](https://user-images.githubusercontent.com/3493868/59981028-bd8e1700-961b-11e9-947a-3a4ad32db132.png)

**Comment by isaacwhite** [comment]
Hi @pranayhere, this is the expected behavior. On the "View all" page (which you can access from the homepage) Library will list all the files in top level folders within your drive. Top level files not in any folder (while searchable) are not listed anywhere.

**Comment by isaacwhite** [comment]
One more thing: based on your screenshot, it sounds like you are expecting files in the drive to show up on the homepage automatically (they don't).The files and folders listed on the homepage are determined by the items in your drive tagged for those locations. See: https://nyt-library-demo.herokuapp.com/how-to-use-library/how-do-i-use-tags
