### ISSUE TITLE
Display a warning when multiple documents resolve to the same path

### ISSUE THREAD

**Issue by isaacwhite** [nytimes/library#4]
### Problem Description
Google Drive allows multiple documents with the same name to exist in the same folder. Library currently only allows a single item to occupy a given path.

### Feature
When this situation happens in a Google Drive or shared folder, Library should detect it and emit a warning that says only one document will be accessible through Library.

**Comment by abstrctn** [comment]
A subtask of this might be to ensure that, if there are multiple documents that match a url, the same document should get chosen every time.

Currently, library seems to vary which of the documents gets shown, which can be confusing.

**Comment by jonpo** [comment]
Google Drive also allows multiple folders of the same name to exist in the same folder. It would be good to also cover that case.

**Comment by isaacwhite** [comment]
Closed via #46 !
