### ISSUE TITLE
Template Customization

### ISSUE THREAD

**Issue by davegonzalez** [nytimes/library#45]
### Problem Description

For users who want to use the underlying Library infrastructure, but be able to give the site their own look and feel, this aims to allow template/layout customization using the existing `custom` folder.

### Feature

One idea on how to implement stems from a previous idea that allowed different sections to use different pages. We could start here: https://github.com/nytimes/library/blob/master/server/routes/categories.js#L28-L29 and potentially extend this to also check the layouts within the custom folder as well.

This is something that I'll start digging into.

**Comment by isaacwhite** [comment]
Closed via #200 🎉
