### ISSUE TITLE
Set a max height for folder views with scroll

### ISSUE THREAD

**Issue by afischer** [nytimes/library#47]
### Problem Description

Currently there is no max height on the boxes that list the contents of folders in the `/categories` view. This can hinder usability and look goofy when there are top-level folders with many items, especially when next to folders containing few items.

### Feature

Add a reasonable `max-height` to the `children-container` class, and set `overflow: scroll`. Additionally, add some indication that the element is scrollable, e.g. a fade-out at the bottom or a permanent scroll bar.

This maximum height should be small enough that sections can be bypassed on mobile devices without having to scroll to the bottom of the scroll view first. (This likely needs some a spec)

**Comment by isaacwhite** [comment]
Left a note on the corresponding PR, but what if we took a slightly different approach here? Quoted from the PR:

> It seems likely to me that when looking for a document in a large folder, rather than scroll through everything in a height-limited window you'd want to just see everything at once. The point about it being unwieldy to have no limit at all is a good one, though.
> 
> I know it would be more complex, but what if we added some logic in the categories page template that hid all of the items after the maximum number? We could combine that logic with the inclusion of a button that would reveal the rest of the documents on demand, to avoid the case where you need to scroll carefully through the height-limited list.

**Comment by afischer** [comment]
Closed with #49!
