### ISSUE TITLE
I installed... now what? There is nothing.

### ISSUE THREAD

**Issue by femans** [nytimes/library#62]
Fully installed using google cloud platform and heroku following the setup guide.
After the - very elaborate and well documented - setup guide there is hardly any documentation on how to proceed. 

### Expected Behavior
I expected to see some app where you can browse and make pages and folders or something. Similar to the documentation pages but then with edit functionality.

### Actual Behavior
Got first a 500 error. Then i tried clicking around, but there is nothing except a search bar that turns up nothing (because there is nothing). 
"get started" link gives a 400 error.

### Additional Information
According to documentation, there should be an add page button, but there is not.
What am I missing?
I also tried adding a page and a folder to the google drive folder to see if it shows up in the app but it does not.
I looked on the google group but it seems there has never been posted anything.

**Comment by isaacwhite** [comment]
Hi @femans, have you consulted the [How to Use Library](https://nyt-library-demo.herokuapp.com/how-to-use-library) section on the demo site? After your copy of Library is set up the instructions in that section should have all you need to get started.

There are a couple things I suspect you're getting tripped up on (which we should [build in some better signaling](https://github.com/nytimes/library/issues/63) around):

- Until there are some documents in your shared folder, Library may return a 500 on the homepage
- New documents don't show up on the Library homepage by default. To get documents to show up in the boxes on the homepage, you need to [use tags](https://nyt-library-demo.herokuapp.com/categories)
- The "Get started" link by default goes to `/get-started`, where it's expected you will want to make your own guide to explain how to use the content in your Library site.
- The "View All Pages" section only shows documents inside top level folders. Documents added to Library are searchable no matter where they are, but are only displayed in a browsable location if they are inside a folder first.

Does that all make sense? It sounds like your next steps should be:

1. Create a new folder inside your Library site (via Google Drive)
2. Create a new document inside that folder, or drag an existing document to that location in Google Drive
3.  Browse to the document (or search for it) in your Library site. _Note: if you are using a shared folder, Library might return a 500 for the first several minutes after moving an existing document while the new permissions propagate on Google's end. This should resolve itself after some time, so you still get a 500 one hour later something else is likely amiss._
