### ISSUE TITLE
Never-edited docs show undefined last editor in search results

### ISSUE THREAD

**Issue by afischer** [nytimes/library#68]
### Context (Environment)

MacOS/Linux, Node 8 - can be seen locally and in production

### Expected Behavior
When searching for documents, a list should be shown with each article's folder and last editor.

### Actual Behavior
If an article is new and has never been edited/only edited once, `undefined` is shown as the last editor.
<img width="100%" alt="Screenshot of search page" src="https://user-images.githubusercontent.com/5422397/66868430-49310800-ef6b-11e9-99c9-df66445ae9b8.png">

### To Reproduce

Create a new page in your drive, and search for its title from in Library.

### Possible Solution

If an article has not been edited, there is currently undefined behavior, but I would advocate either
- show nothing, or
- show the author name instead

**Comment by alexwgraves** [comment]
This issue is not reproducible when using `DRIVE_TYPE=folder`. It seems likely that this bug only occurs on team drives.
