### ISSUE TITLE
Support Node 12 

### ISSUE THREAD

**Issue by afischer** [nytimes/library#75]
### Problem Description

Library officially currently supports LTS Node versions 8 and 10. [Node 8 is in maintenance mode](https://nodejs.org/en/about/releases/) with an end-of-life planned for April 2020 

### Feature
Since Node 12 is the current LTS version, we should support it. We should
- Update any dependencies that are rely on libraries not compatible with Node 12
- Enable a Node 12 environment in Travis

### Additional Information
Attempting to run the app on Node 12 on my MacOS 10.14 machine, I had to rebuild node-sass before the app would start, which would eventually fail due to dependency gRPC. Rebuilding gRPC fails on my machine.

**Comment by patcon** [comment]
Same. xcode failures mentioning gRPC and node-gyp led me to work with most recent stable v10 instead of v12, and it installed fine :)
