### ISSUE TITLE
Document creation timestamps

### ISSUE THREAD

**Issue by afischer** [nytimes/library#76]
### Problem Description
An issue discussed on the [October community call](https://nyt-library-demo.herokuapp.com/the-library-team/community-calls/community-call-oct-15) was that it is often difficult to determine if documentation is outdated. A good first step to provide some additional clarity here would be to include creation dates on document pages.

### Feature
Maybe something like this?
<img width="411" alt="Mock up of what a timestamp may look like" src="https://user-images.githubusercontent.com/5422397/67641569-268edf80-f8d9-11e9-90bd-5beebf7fe033.png">
Not sure if an exact date or a relative timestamps with alt-text showing the exact date would be more useful in this scenario.

**Comment by isaacwhite** [comment]
One complication here is Library also supports manual bylines. So, a document could include the line:

> By Andrew Fischer

even if it had a different original creator, to indicate ownership. Is there another phrasing we could do to separate those elements? One possibility:

> By Andrew Fischer
> Last edited by John Doe a few seconds ago.  Created on Oct 12, 2014.

cc: @alexwgraves

**Comment by alexwgraves** [comment]
That makes sense. I'll move the created timestamp from the `<p>` with the `byline` variable and add it below.
