### ISSUE TITLE
Update Heroku deployment template DRIVE_TYPE instructions

### ISSUE THREAD

**Issue by maxine** [nytimes/library#82]
Change the instructions for `DRIVE_TYPE` env var in the Heroku deployment template to: “Set this value to ``folder`` if your documents are in a shared folder or ``team`` for a team drive”. Right now it says to set the value to ``shared`` instead of ``folder``. I'll add a new screenshot in the [demo site Heroku deployment instructions](https://nyt-library-demo.herokuapp.com/get-started/deploying-library-heroku) once this gets updated!

<img width="572" alt="Screen Shot 2019-03-15 at 9 23 45 AM" src="https://user-images.githubusercontent.com/23054741/68603767-93c07a00-046e-11ea-84a1-100d116aaaab.png">

cc: @isaacwhite

**Comment by isaacwhite** [comment]
Closed via https://github.com/nytimes/library/commit/a75537ca94e30e555c522fb5683d85fd538249f1#diff-6a1b6963e828b69fcc667e3c45df78bb
