### ISSUE TITLE
Library doesn't handle "number-only" folder names

### ISSUE THREAD

**Issue by SMores** [nytimes/library#9]
### Context (Environment)
Used "Deploy to Heroku" button with no customization

### Expected Behavior
Folders whose names consist of only numbers should be rendered, indexed, and slugged correctly.

### Actual Behavior
Folders whose names consist of only numbers are displayed as empty strings in browsing (see screenshot) and are dropped from slugs (e.g. `exec-agendas/2018/exec-agenda` -> `exec-agendas/exec-agenda`).

![empty name](https://user-images.githubusercontent.com/5354254/54839471-4e61f900-4ca1-11e9-9234-e88acc2f1878.png)

### To Reproduce
Create a folder whose name consists of only numbers (e.g. "2018") and attempt to navigate to it or any file in it in Library.

**Comment by isaacwhite** [comment]
Thanks for flagging! Will address this in the 1.0.2 release.
