### ISSUE TITLE
Getting "Uh oh, that's a 500" - new installation on GCP

### ISSUE THREAD

**Issue by tomcoombs** [nytimes/library#95]
### Context (Environment)
I've followed the instructions to install Library on GCP. It seemed to all go ok.
It's pointing to a Shared Drive on google drive.
in .env I put ... 
  DRIVE_TYPE=folder
  DRIVE_ID= < the long ID in the URL when I go to the shared folder in a browser >

I've anonymized this, but here's how the .env looks ...

![image](https://user-images.githubusercontent.com/1791273/74392982-1e3cbf00-4e4c-11ea-8390-997cbe6f1a86.png)

### Expected Behavior
When I go to the URL for my library site I was expecting to see the site load up much like the one in the instructions/demo.

### Actual Behavior
I see the site load but it just says "Uh oh, that's a 500"

![image](https://user-images.githubusercontent.com/1791273/74392520-c94c7900-4e4a-11ea-8ae3-a4cd90f268c4.png)

I'm not very familiar with GCP, so I don't know where to get logs.

![image](https://user-images.githubusercontent.com/1791273/74392722-63142600-4e4b-11ea-8fb8-ad1729b1c1eb.png)
 

### To Reproduce
nothing to add here

### Additional Information
none

### Possible Solution
I see isaacwhite's note on here https://github.com/nytimes/library/issues/63
and it sounds like I might have that problem. My shared drive was empty, but I added a single doc file now. It still shows the 500 error.
Also, that post mentions labelling. I don't know what this means. If it's important, it could be my problem.

thank you.

**Comment by isaacwhite** [comment]
Hi @tomcoombs, it's hard to know for sure without seeing the logs, but one other thing that could be going wrong is the line breaks in your .env file. 

Could you try removing the line breaks (with `\n` characters as necessary within the private key) and redeploying and let me know if that resolves? 

In the past we've seen that `dotenv` (used to set the env vars in the GAE instructions) doesn't automatically handle the line breaks and might pass along partial values for the environment variables.

**Comment by tomcoombs** [comment]
Thanks for your quick response @isaacwhite.

I did as you suggested and took out all the line breaks, but unfortunately I still get the same 500 error page.

I'd be happy to grab the logs. Would you be able to point me to where they are?

![image](https://user-images.githubusercontent.com/1791273/74395543-f866e880-4e52-11ea-9193-7793ae8bfc68.png)

**Comment by isaacwhite** [comment]
I think you can find those under the Stackdriver option in the sidebar of the Google Cloud console. I went to Stackdriver > Logs > Logs viewer to see the  ones from App Engine.

**Comment by tomcoombs** [comment]
Thanks, I found them.

It had one error saying I hadn't enabled Drive API. Maybe I missed that. Anyway I did it and that error has gone. But, I'm still getting the 500 page. The logs are showing ...

![image](https://user-images.githubusercontent.com/1791273/74397687-a0cb7b80-4e58-11ea-9cf8-1d302e026758.png)

**Comment by isaacwhite** [comment]
The logs suggest that there are two issues, perhaps related.

The `Unexpected end of JSON input` suggests that the GOOGLE_APPLICATION_JSON is malformed, perhaps because the line breaks (or singlequotes?) are causing an issue.

The other message, `secret option required for session`, suggests the `SESSION_SECRET` environment is not set. The oauth integration provided with Library out of the box requires this.

Could you try it again after changing both of those? 

Does the app work when you run it locally? That might also suggest more specific debugging steps.

**Comment by tomcoombs** [comment]
Thanks for all your help @isaacwhite.

I fixed the issues you suggested, and a couple more along the way. I've documented them below in case it helps anyone else.

I'm still getting a 500 page. Now the logs show ...

'TypeError: Cannot convert undefined or null to object\n at Function.keys (<anonymous>)\n at buildDisplayCategories (/srv/server/routes/pages.js:58:29)\n at handlePage (/srv/server/routes/pages.js:49:24)' }

![image](https://user-images.githubusercontent.com/1791273/74494713-15fe8580-4f19-11ea-8660-682281d988d0.png)


![image](https://user-images.githubusercontent.com/1791273/74494324-10ed0680-4f18-11ea-924e-6643a95f6ff1.png)


--------
Just for info, the various issues that I think are fixed ...

I did have single quotes here ...
`GOOGLE_APPLICATION_JSON='{"type": "service_ac ....... iceaccount.com"}'`
But I've taken them out ...
`GOOGLE_APPLICATION_JSON={"type": "service_ac ....... iceaccount.com"}`
This page shows single quotes https://nyt-library-demo.herokuapp.com/get-started/deploying-library-google-app-engine. I hadn't seen this page until now, but this doesn't show them https://nyt-library-demo.herokuapp.com/about-this-site/environment-variables

Then when I loaded the site I got a 400 error and "the redirect_uri is not configured" or something similar. I went to the Google credentials page and added my Library URL as an authorized redirect_uri. (This is probably a basic error, but I'm not that familiar with these things).

I also had in my .env
APPROVED_DOMAINS=mydomaincom
which I copied from https://nyt-library-demo.herokuapp.com/get-started/deploying-library-google-app-engine, but I see in the readme that it should be
APPROVED_DOMAINS="mydomain.com"

**Comment by tomcoombs** [comment]
I found the problem. I had ...
`DRIVE_TYPE=folder`
but it should have been ...
`DRIVE_TYPE=team`

It seems Google [changed the name](https://gsuiteupdates.googleblog.com/2019/04/shared-drives.html) of "team drive" to "shared drive".

I'm up and running now. Thanks for all your help @isaacwhite.

**Comment by isaacwhite** [comment]
Glad to hear you got it all working! Thanks also for your notes; I've added them to #63, which we're using to track similar documentation updates.
