### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by MSch** [nytimes/library#99]
We're running library on Heroku, and recently upgraded from https://github.com/nytimes/library/commit/a4f9e4255c0a6e48df8b7a5e92f128256b408280 to the latest master https://github.com/nytimes/library/commit/5015b9e7050e990bf70aa1864078674b9d5fed09.

There is only one significant change in this diff: https://github.com/nytimes/library/pull/92

Since upgrading it seems some of the formatter logic that strips out superfluous html tags is broken, though I'm not familiar enough with the code base to pinpoint it exactly.

Specifically, we are seeing `<a>` tags that don't belong in the body:

<table><tr><td>
<img width="400" alt="Screenshot 2020-03-06 at 20 40 51" src="https://user-images.githubusercontent.com/7475/76116744-d6dcc500-5fea-11ea-96ea-50fb2c16b37c.png">
</td></tr></table>

The relevant HTML looks like this:

<img width="433" alt="Screenshot 2020-03-06 at 20 41 21" src="https://user-images.githubusercontent.com/7475/76116809-e956fe80-5fea-11ea-9067-162c2c2899e6.png">

Downgrading restores the expected behavior:

<table><tr><td>
<img width="400" alt="Screenshot 2020-03-06 at 20 44 44" src="https://user-images.githubusercontent.com/7475/76117052-5f5b6580-5feb-11ea-8ac3-e5474d795541.png">
</td></tr></table>

<img width="369" alt="Screenshot 2020-03-06 at 20 42 08" src="https://user-images.githubusercontent.com/7475/76116886-04c20980-5feb-11ea-9110-2839208b3984.png">

Please also note the difference in spacing between paragraphs. It seems #92 changes behavior and doesn't include empty `<p>`s between paragraphs any more.

Please let me know if there's any way we can help in diagnosing this issue. Thank you for building and open sourcing this amazing project.

**Comment by TylerFisher** [comment]
+1, seeing similar issues with the current version of Library.

**Comment by isaacwhite** [comment]
Thanks for letting us know about this! I was able to reproduce this and [opened a PR](https://github.com/nytimes/library/pull/100) to address. 

Seems like the underlying problem is our HTML parsing library got changed to XML mode and started self closing `a` tags, which is only allowed in XHTML.

**Comment by MSch** [comment]
I can confirm that this is fixed. Thank you so much!
